### ISSUE TITLE
OutOfMemoryError: .pst format

### ISSUE THREAD

**Issue by dietzc** [scifio/scifio-bf-compat#11]
The following exception is thrown when I try to read in .pst files:

java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at loci.poi.poifs.storage.HeaderBlockReader.<init>(HeaderBlockReader.java:97)
	at loci.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:114)
	at loci.formats.services.POIServiceImpl.initialize(POIServiceImpl.java:86)
	at loci.formats.services.POIServiceImpl.initialize(POIServiceImpl.java:73)
	at loci.formats.in.TillVisionReader.initFile(TillVisionReader.java:227)
	at loci.formats.FormatReader.setId(FormatReader.java:1317)
	at loci.formats.ImageReader.setId(ImageReader.java:753)
	at io.scif.bf.BioFormatsFormat$Parser.typedParse(BioFormatsFormat.java:405)
	at io.scif.bf.BioFormatsFormat$Parser.typedParse(BioFormatsFormat.java:387)
	at io.scif.AbstractParser.parse(AbstractParser.java:252)
	at io.scif.AbstractParser.parse(AbstractParser.java:220)
	at io.scif.AbstractParser.parse(AbstractParser.java:316)
	at io.scif.AbstractParser.parse(AbstractParser.java:52)
	at org.knime.knip.io.ScifioImgSource.getReader(ScifioImgSource.java:401)
	at org.knime.knip.io.ScifioImgSource.getSeriesCount(ScifioImgSource.java:219)
	at org.knime.knip.io.nodes.imgreader.ReadFileImgTable$2.next(ReadFileImgTable.java:384)
	at org.knime.core.node.ExecutionContext.createBufferedDataTable(ExecutionContext.java:245)
	at org.knime.knip.io.nodes.imgreader.ImgReaderNodeModel.execute(ImgReaderNodeModel.java:402)
	at org.knime.core.node.NodeModel.execute(NodeModel.java:706)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:555)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1131)
	at org.knime.core.node.Node.execute(Node.java:927)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:559)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:125)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:248)

I uploaded a sample to FIJI (dbb4A.pst)!

**Comment by hinerm** [comment]
Looks like a bug in Bio-Formats. This fails with `File > Import > Bio-Formats` as well. No extra config from SCIFIO is causing this failure - it's just a result of setId on this file.

You'll have to use [the bio-formats bug reporting system](http://www.openmicroscopy.org/site/support/bio-formats5/about/bug-reporting.html).

Sorry @dietzc  :(
