### ISSUE TITLE
NoSuchMethod: loci.formats.FormatTools.getPhysicalSizeX(Ljava/lang/Double;Ljava/lang/String;)Lome/units/quantity/Length;

### ISSUE THREAD

**Issue by dietzc** [scifio/scifio-bf-compat#14]
Hi @hinerm,

I just updated the dependencies of KNIME Image Processing to pom-imagej 7.1.0. Since then, when I try to read in a Tiff-File I get the following stack-trace:

`java.lang.NoSuchMethodError: loci.formats.FormatTools.getPhysicalSizeX(Ljava/lang/Double;Ljava/lang/String;)Lome/units/quantity/Length;
	at loci.formats.in.BaseTiffReader.initMetadataStore(BaseTiffReader.java:469)
	at loci.formats.in.SISReader.initMetadataStore(SISReader.java:237)
	at loci.formats.in.BaseTiffReader.initMetadata(BaseTiffReader.java:98)
	at loci.formats.in.BaseTiffReader.initFile(BaseTiffReader.java:576)
	at loci.formats.FormatReader.setId(FormatReader.java:1395)
	at loci.formats.ImageReader.setId(ImageReader.java:835)
	at io.scif.bf.BioFormatsFormat$Parser.typedParse(BioFormatsFormat.java:424)
	at io.scif.bf.BioFormatsFormat$Parser.typedParse(BioFormatsFormat.java:406)
	at io.scif.AbstractParser.parse(AbstractParser.java:253)
	at io.scif.AbstractParser.parse(AbstractParser.java:220)
	at io.scif.AbstractParser.parse(AbstractParser.java:317)
	at io.scif.AbstractParser.parse(AbstractParser.java:52)
	at org.knime.knip.io.ScifioImgSource.getReader(ScifioImgSource.java:401)
	at org.knime.knip.io.ScifioImgSource.getSeriesCount(ScifioImgSource.java:219)
	at org.knime.knip.io.nodes.imgreader.ReadFileImgTable$2.next(ReadFileImgTable.java:431)
	at org.knime.core.node.ExecutionContext.createBufferedDataTable(ExecutionContext.java:245)
	at org.knime.knip.io.nodes.imgreader.ImgReaderNodeModel.execute(ImgReaderNodeModel.java:353)
	at org.knime.core.node.NodeModel.execute(NodeModel.java:706)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:555)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1131)
	at org.knime.core.node.Node.execute(Node.java:927)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:559)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:125)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:248)`

Actually, I think the method in `FormatTools` as changed (`String unit` removed), but the `BaseTiffReader` has not been updated / released accordingly?

Thanks for your help,

Christian

**Comment by dscho** [comment]
> loci.formats.FormatTools.getPhysicalSizeX(Ljava/lang/Double;Ljava/lang/String;)Lome/units/quantity/Length;

This is an API change in Bio-Formats 5.x, therefore it appears there is a version skew in your setup: your code was compiled against Bio-Formats 4.x but tries to run against Bio-Formats 5.x.

I fixed the calls in OpenSPIM thusly: https://github.com/openspim/SPIMAcquisition/commit/580505d97238602aad3781f1f712dbf5f5237582

In your setup, there is probably some problem with incorrectly-defined dependency chains.

**Comment by dietzc** [comment]
Yes, this is what I supposed. But actually, I'm using all the versions from the latest ImageJ-Pom and I didn't define any version on my own?!

**Comment by dietzc** [comment]
I think the `BaseTiffReader` which is part of scifio-bf-compat still relies on the old API?

**Comment by hinerm** [comment]
@dietzc you have a [5.1.1 formats-bsd](https://github.com/openmicroscopy/bioformats/blob/v5.1.1/components/formats-bsd/src/loci/formats/in/BaseTiffReader.java#L469) and [5.1.0 formats-api](https://github.com/openmicroscopy/bioformats/blob/v5.1.0/components/formats-api/src/loci/formats/FormatTools.java#L1388)

@dscho is correct that there is version skew in your project. Although `scifio-bf-compat` does still depend on `5.1.0`, if everything was being resolved by the pom this dependency would be managed to `5.1.1` correctly (for example, check out [Fiji.git](https://github.com/fiji/fiji) and do a `mvn dependency:tree -Dverbose`)

So how are you actually consuming pom-imagej? Do you have any dependencies explicitly declared? Is anything pinned to specific versions? Can you point me to it in [knime-ip](https://github.com/knime-ip)?

**Comment by dietzc** [comment]
No manually defined dependencies. Just consuming imagej-pom. However, I am sure its something on our side. Here is our POM https://github.com/knime-ip/knip-externals/blob/master/autogen/pom.xml

**Comment by hinerm** [comment]
@dietzc `mvn dependency:tree -Dverbose` on that pom shows no dependency on scifio-bf-compat. This makes sense given that it's extending pom-imagej and does not declare a dependency on scifio-bf-compat.

Since you use scifio-bf-compat and it's not being managed by this pom it is certainly vulnerable to skew. Your pom should add a runtime dependency, like [in Fiji](https://github.com/fiji/fiji/blob/master/pom.xml#L682-686).

**Comment by dietzc** [comment]
Well the POM which has a dependency in scifio-bf-compat is auto generated from this POM. Anyway, i will try to Figure it out.

**Comment by hinerm** [comment]
auto-generated how though? where's the pom with the scifio-bf-compat dep?

**Comment by ctrueden** [comment]
One way to sidestep this issue would be to extend `pom-fiji` instead of `pom-imagej`. It would be a bit overkill, but you'd get the `scifio-bf-compat` version managed for you. Alternately, we could migrate management of `scifio-bf-compat` into `pom-scijava`—@hinerm, can you think of any reason not to do that actually? Would make people's lives easier.

**Comment by hinerm** [comment]
@ctrueden Unless I'm missing something, I don't think moving `scifio-bf-compat` management wouldn't help @dietzc here. `scifio-bf-compat` is managed in [pom-imagej](https://github.com/imagej/pom-imagej/blob/pom-imagej-7.1.0/pom.xml#L307) which this pom is extending. I suspect it's a problem in the autogeneration resolving dependencies different than Maven... but that's just a theory.

**Comment by ctrueden** [comment]
@hinerm Nope, you didn't miss anything. My comment above is completely and utterly off-base. A wizard did it.

**Comment by dietzc** [comment]
hi all,
first of all: thanks for your help and sorry for the short replies. I was travelling. Anyway, it seems that in our build system (and therefore actually in maven) the order of the managed bundles seems to matter. 

About our process: We first auto-generate a bunch of poms (defined in the folder bundle-groups) by building the pom.xml in the autogen folder. the resulting pom in the target folder then contains all dependencies. Anyway, it seems to work now. Thanks for your help!

Christian
